# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5db1f788420572db5c424387f73c9d1e0de001a92581b74b23e097ed9d689150f7437fafea2d1ef25b87ec657f6fff96362245720a3e028a12782e6770e9683

test:
  secret_key_base: 3fb1c0513688bb3da8b184b7deca7bc83476efbaec1b1407fb0e740fe4d0cbb9770953d5c71020d746f45b1f48d28905b6c21929dfa79065b4bda0c702838665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
